import fs from 'node:fs';
import path from 'node:path';

import {config as dotenvConfig} from 'dotenv';

import UpsunDocCommand from '../../base-command.js';
import {globalExamples} from '../../config.js';
import Logger from '../../utils/logger.js';

export default class ConfigGenerate extends UpsunDocCommand {
  static override description = 'Generate configuration file from environment variables';
  static override examples = ['<%= config.bin %> <%= command.id %>', ...globalExamples];

  private logger!: Logger;

  public async run(): Promise<void> {
    await this.parse(ConfigGenerate);

    this.logger = new Logger('config:generate');

    try {
      // Load environment variables from .env file
      const workspaceRoot = process.cwd();
      const envPath = path.join(workspaceRoot, '.env');
      dotenvConfig({path: envPath});

      // Get values from environment or use defaults
      const config = {
        vendorName: process.env.VENDOR_NAME || 'Upsun',
        configFiles: {
          app: process.env.CONFIG_FILE_APP || '.upsun/config.yaml',
          services: process.env.CONFIG_FILE_SERVICES || '.upsun/config.yaml',
        },
        glossary: {
          mb: process.env.GLOSSARY_MB || 'MB',
        },
        vendor: {
          discord: {
            url: process.env.VENDOR_DISCORD_URL || 'https://discord.gg/platformsh',
          },
          hostname: process.env.VENDOR_HOSTNAME || 'platformsh.site',
        },
      };

      // Generate the config.jsx file content
      const configContent = `// This file is auto-generated by config:generate command
// Do not edit manually - changes will be overwritten

export const config = ${JSON.stringify(config, null, 2)};
`;

      // Write the file
      const outputPath = path.join(workspaceRoot, 'contents', 'snippets', '.cache', 'config.jsx');
      const outputDir = path.dirname(outputPath);

      // Ensure the .cache directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, {recursive: true});
      }

      fs.writeFileSync(outputPath, configContent, 'utf8');

      this.logger.success('Generated config.jsx with environment variables');
      this.logger.info(`  VENDOR_NAME: ${config.vendorName}`);
      this.logger.info(`  Output: ${path.relative(workspaceRoot, outputPath)}`);
    } catch (error) {
      this.logger.error('Failed to generate config.jsx');
      if (error instanceof Error) {
        this.logger.error(error.message);
      }

      throw error;
    }
  }
}
